# Generated by Django 5.0.4 on 2024-04-08 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("nome", models.CharField(max_length=120)),
                ("idade", models.IntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=25,
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=50, null=True)),
                ("data_de_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
