# Generated by Django 5.0.4 on 2024-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vidas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vida",
            name="integracao",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Integrado", "Integrado"),
                    ("Revisar", "Revisar"),
                ],
                default="Pendente",
                max_length=9,
            ),
        ),
    ]
